name: ikleeralles
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  intl: ^0.16.1
  flutter_i18n: ^0.8.3
  flutter_webview_plugin: ^0.3.11
  scoped_model: ^1.0.1
  auto_size_text: ^2.1.0
  dotted_border: ^1.0.6
  flutter_svg: ^0.18.0
  flutter_slidable: ^0.5.7
  flutter_stetho: ^0.6.0-dev.1
  fluttertoast: ^7.1.1
  keyboard_actions: ^3.3.1
  material_segmented_control: ^2.1.0
  diacritic: ^0.1.1
  audioplayers: ^0.16.2
  purchases_flutter: ^1.3.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Ikleeralles"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/launcher.png"
  image_path_android: "assets/images/launcher.png"
  adaptive_icon_background: "assets/images/android_launcher_background.png"
  adaptive_icon_foreground: "assets/images/android_launcher_foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/images/
    - assets/i18n/
    - assets/svg/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700

    - family: Kreon
      fonts:
        - asset: assets/fonts/Kreon/Kreon-Light.ttf
          weight: 300
        - asset: assets/fonts/Kreon/Kreon-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kreon/Kreon-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kreon/Kreon-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kreon/Kreon-Bold.ttf
          weight: 700

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans/WorkSans-Black.ttf
          weight: 900
    - family: JustAnotherHand
      fonts:
        - asset: assets/fonts/JustAnotherHand/JustAnotherHand-Regular.ttf
  uses-material-design: true

